version: '3'
services:
  react_app:
    build:
      context: .
    container_name: react_app
    command: "npm start"
    expose:
      - "3000"
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules