version: '3'
services:
  react_app_music:
    build:
      context: .
    container_name: react_app_music
    command: "npm start"
    expose:
      - "3000"
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app
      - /app/node_modules
